### PR TITLE
Fix compatibility with ActiveRecord 7.2

### LINKED ISSUE #536: Rails 7.2: wrong number of arguments (given 2, expected 1)
After upgrading from rails 7.1.3.4 to rails 7.2.0.beta1, PgSearch.multisearch generates the following error: 
`wrong number of arguments (given 2, expected 1)`

My exact code is:
`results = PgSearch.multisearch(@query).where(account_id: current_account.id)`

Works with no issue on rails 7.1x

### PR DESCRIPTION
**Pull request by fatkodima**
The interface for `Or` arel node was changed in https://github.com/rails/rails/pull/51492.
This currently prevents our upgrade to rails 7.2.

Fixes #536.

### CODE REVIEW

File: lib/pg_search/scope_options.rb [hunk 1]
```diff
@@ -90,10 +90,17 @@ def subquery
...
-        .reject { |_feature_name, feature_options| feature_options && feature_options[:sort_only] }
-        .map { |feature_name, _feature_options| feature_for(feature_name).conditions }
-        .inject { |accumulator, expression| Arel::Nodes::Or.new(accumulator, expression) }
+      expressions =
+        config.features
+          .reject { |_feature_name, feature_options| feature_options && feature_options[:sort_only] }
+          .map { |feature_name, _feature_options| feature_for(feature_name).conditions }
+
+      # https://github.com/rails/rails/pull/51492
+      if ActiveRecord.version >= Gem::Version.new("7.2.0.beta1")
```
Comment (nertzy) [inline lib/pg_search/scope_options.rb:99]: This is great! I'm wondering, should we change this to check Arel's version instead?

**Comment by nertzy** [comment]
Also it looks like the `undercover` code coverage tool is getting triggered for the new branch not having code coverage on both sides, but that doesn't make sense in this case so I'll have to figure out a way to improve that gate or disable it here.

File: lib/pg_search/scope_options.rb (hunk 1 above)
Comment (fatkodima) [reply lib/pg_search/scope_options.rb:99]: No, because the arel version hasn't changed in 6 years (from git blame).

**Comment by fatkodima** [comment]
I once was convinced that code coverage tools are pretty useless, especially for caring too much about its numbers (if it becomes higher/lower or should be 99%). 🤷 
Imo, only like running it locally for yourself to verify that you actually tested what you wanted is useful.

**Comment by fatkodima** [comment]
@nertzy Sorry for pinging, but can you reconsider this PR and release a new version with the fix?

**Comment by nertzy** [comment]
Thanks! I updated the implementation to do a single check at require time, and based it on a direct arity check of the constructor instead of using the version.

Looks great, thanks for this fix!

**Comment by fatkodima** [comment]
Thank you ❤️
